// <auto-generated />
using AshmesMarketplaces.DataAccess;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AshmesMarketplaces.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614154500_ParserVisibleDeliveryStatus")]
    partial class ParserVisibleDeliveryStatus
    {
    }
}
