// <auto-generated />
using System;
using System.Text.Json;
using AshmesMarketplaces.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AshmesMarketplaces.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518152454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Domain")
                        .HasColumnType("integer")
                        .HasColumnName("domain");

                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.PermissionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Permissions_Categories", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.RolePermission", b =>
                {
                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid")
                        .HasColumnName("id_role");

                    b.Property<Guid>("IdPermission")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permission");

                    b.HasKey("IdRole", "IdPermission");

                    b.HasIndex("IdPermission");

                    b.ToTable("Roles_Permissions", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.RoleSubrole", b =>
                {
                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid")
                        .HasColumnName("id_role");

                    b.Property<Guid>("IdSubrole")
                        .HasColumnType("uuid")
                        .HasColumnName("id_subrole");

                    b.HasKey("IdRole", "IdSubrole");

                    b.HasIndex("IdSubrole");

                    b.ToTable("Role_Subroles", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Advertising.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<Guid?>("IdSetCampaign")
                        .HasColumnType("uuid")
                        .HasColumnName("id_set_campaign");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<JsonDocument>("TimeToImpression")
                        .HasColumnType("jsonb")
                        .HasColumnName("time_to_impression");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSetCampaign");

                    b.ToTable("Campaign", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Advertising.CampaignMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ClicksAmount")
                        .HasColumnType("integer")
                        .HasColumnName("clicks_amount");

                    b.Property<decimal?>("CostDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_day");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("IdCampaign")
                        .HasColumnType("uuid")
                        .HasColumnName("id_campaign");

                    b.Property<int?>("ImpressionAmount")
                        .HasColumnType("integer")
                        .HasColumnName("impression_amount");

                    b.HasKey("Id");

                    b.HasIndex("IdCampaign");

                    b.ToTable("Metrics_Campaign", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Finance.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DatePay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_pay");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("IdCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.Property<Guid>("IdCreator")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creator");

                    b.Property<Guid?>("IdResponsible")
                        .HasColumnType("uuid")
                        .HasColumnName("id_responsible");

                    b.Property<Guid>("IdWorkspace")
                        .HasColumnType("uuid")
                        .HasColumnName("id_workspace");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdResponsible");

                    b.HasIndex("IdWorkspace");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Finance.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Categories_Expenses", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Logistics.Logistic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostLogistic")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_logistic");

                    b.Property<decimal?>("CostStorage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_storage");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<Guid?>("IdWarehouse")
                        .HasColumnType("uuid")
                        .HasColumnName("id_warehouse");

                    b.Property<int?>("StockAmount")
                        .HasColumnType("integer")
                        .HasColumnName("stock_amount");

                    b.Property<int>("StockAmountStatistic")
                        .HasColumnType("integer")
                        .HasColumnName("stock_amount_statistic");

                    b.Property<int?>("StockInTransit")
                        .HasColumnType("integer")
                        .HasColumnName("stock_in_transit");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Logistics", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("country");

                    b.Property<DateTime>("DateMpRegistration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_mp_registration");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("RateRedemption")
                        .HasColumnType("integer")
                        .HasColumnName("rate_redemption");

                    b.Property<int>("SalesAmount")
                        .HasColumnType("integer")
                        .HasColumnName("sales_amount");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.BrandMarketplace", b =>
                {
                    b.Property<Guid>("IdMp")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mp");

                    b.Property<Guid>("IdBrand")
                        .HasColumnType("uuid")
                        .HasColumnName("id_brand");

                    b.Property<string>("IdOnMp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_on_mp");

                    b.HasKey("IdMp", "IdBrand");

                    b.HasIndex("IdBrand");

                    b.ToTable("Brands_Marketplaces", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("IdOnMp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_on_mp");

                    b.Property<Guid?>("IdParentCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("id_parent_category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IdParentCategory");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Marketplace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("api_url");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_version");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<string>("SchemeDelivery")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scheme_delivery");

                    b.Property<int>("TypeCommission")
                        .HasColumnType("integer")
                        .HasColumnName("type_commission");

                    b.HasKey("Id");

                    b.ToTable("Marketplaces", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<Guid>("IdMp")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mp");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Latitude")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdMp");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_closed");

                    b.Property<DateTime?>("DateDelivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_delivered");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_opened");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<string>("LocationDestination")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_destination");

                    b.Property<string>("LocationSource")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_source");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<JsonDocument>("Characteristics")
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics");

                    b.Property<int?>("Commission")
                        .HasColumnType("integer")
                        .HasColumnName("commission");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("IdBrand")
                        .HasColumnType("uuid")
                        .HasColumnName("id_brand");

                    b.Property<Guid?>("IdCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.Property<Guid>("IdMp")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mp");

                    b.Property<string>("IdOnMp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_on_mp");

                    b.Property<Guid?>("IdSetPrice")
                        .HasColumnType("uuid")
                        .HasColumnName("id_set_price");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<Guid?>("IdWorkspace")
                        .HasColumnType("uuid")
                        .HasColumnName("id_workspace");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SkuProduct")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku_product");

                    b.Property<string>("SkuSeller")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku_seller");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdMp");

                    b.HasIndex("IdSetPrice");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdWorkspace");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Discount")
                        .HasColumnType("integer")
                        .HasColumnName("discount");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsAutoDiscountActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_discount_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Products_Historical", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("ProductVideos", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Recommendations.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<JsonDocument>("Explanation")
                        .HasColumnType("jsonb")
                        .HasColumnName("explanation");

                    b.Property<Guid>("IdModel")
                        .HasColumnType("uuid")
                        .HasColumnName("id_model");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("score");

                    b.Property<JsonDocument>("Snapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("TypeObject")
                        .HasColumnType("integer")
                        .HasColumnName("type_object");

                    b.HasKey("Id");

                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Recommendations.RecommendationCategory", b =>
                {
                    b.Property<Guid>("IdRecommendation")
                        .HasColumnType("uuid")
                        .HasColumnName("id_recommendation");

                    b.Property<Guid>("IdCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("id_category");

                    b.HasKey("IdRecommendation", "IdCategory");

                    b.HasIndex("IdCategory");

                    b.ToTable("Recommendation_Categories", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Recommendations.RecommendationProduct", b =>
                {
                    b.Property<Guid>("IdRecommendation")
                        .HasColumnType("uuid")
                        .HasColumnName("id_recommendation");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.HasKey("IdRecommendation", "IdProduct");

                    b.HasIndex("IdProduct");

                    b.ToTable("Recommendation_Products", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime?>("DateReply")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reply");

                    b.Property<string>("IdOnMp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_on_mp");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("id_product");

                    b.Property<bool>("IsReplied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replied");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Reviews.ReviewReply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("IdOnMp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_on_mp");

                    b.Property<Guid>("IdReview")
                        .HasColumnType("uuid")
                        .HasColumnName("id_review");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("IdReview");

                    b.ToTable("Reply", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Domain")
                        .HasColumnType("integer")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Rules.RuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Rules.RuleSetRule", b =>
                {
                    b.Property<Guid>("IdSet")
                        .HasColumnType("uuid")
                        .HasColumnName("id_set");

                    b.Property<Guid>("IdRule")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rule");

                    b.HasKey("IdSet", "IdRule");

                    b.HasIndex("IdRule");

                    b.ToTable("Sets_Rules", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Users.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("agent");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expires");

                    b.Property<DateTime?>("DateRefreshed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_refreshed");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_login");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid")
                        .HasColumnName("id_role");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Workspaces.UserWorkspace", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<Guid>("IdWorkspace")
                        .HasColumnType("uuid")
                        .HasColumnName("id_workspace");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid")
                        .HasColumnName("id_role");

                    b.HasKey("IdUser", "IdWorkspace");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdWorkspace");

                    b.ToTable("Users_Workspaces", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("IdBrand")
                        .HasColumnType("uuid")
                        .HasColumnName("id_brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UrlInvite")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_invite");

                    b.HasKey("Id");

                    b.HasIndex("IdBrand");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.Permission", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.PermissionCategory", null)
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.RolePermission", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Permission", null)
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Access.RoleSubrole", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("IdSubrole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Advertising.Campaign", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Rules.RuleSet", null)
                        .WithMany()
                        .HasForeignKey("IdSetCampaign")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Advertising.CampaignMetric", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Advertising.Campaign", null)
                        .WithMany()
                        .HasForeignKey("IdCampaign")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Finance.Expense", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Finance.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("IdCreator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("IdResponsible")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("IdWorkspace")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Logistics.Logistic", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.BrandMarketplace", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Brand", null)
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Marketplace", null)
                        .WithMany()
                        .HasForeignKey("IdMp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Category", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Category", null)
                        .WithMany()
                        .HasForeignKey("IdParentCategory")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Marketplaces.Warehouse", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Marketplace", null)
                        .WithMany()
                        .HasForeignKey("IdMp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.Product", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Brand", null)
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Category", null)
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Marketplace", null)
                        .WithMany()
                        .HasForeignKey("IdMp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Rules.RuleSet", null)
                        .WithMany()
                        .HasForeignKey("IdSetPrice")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("IdWorkspace")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductHistory", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductImage", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.ProductVideo", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany("Videos")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Recommendations.RecommendationCategory", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Category", null)
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Recommendations.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("IdRecommendation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Recommendations.RecommendationProduct", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Recommendations.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("IdRecommendation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Product.Product", null)
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Reviews.ReviewReply", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Reviews.Review", null)
                        .WithMany()
                        .HasForeignKey("IdReview")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Rules.RuleSetRule", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Rules.Rule", null)
                        .WithMany()
                        .HasForeignKey("IdRule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Rules.RuleSet", null)
                        .WithMany()
                        .HasForeignKey("IdSet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Users.Session", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Workspaces.UserWorkspace", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AshmesMarketplaces.Domain.Entities.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("IdWorkspace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Workspaces.Workspace", b =>
                {
                    b.HasOne("AshmesMarketplaces.Domain.Entities.Marketplaces.Brand", null)
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AshmesMarketplaces.Domain.Entities.Product.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
