<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="AshmesMarketplaces.DataAccess\" />
      <Folder Include="AshmesMarketplaces.Infrastructure\" />
    </ItemGroup>

</Project>
